import "./globals.css";
import { Inter, Poppins, Montserrat } from "next/font/google";
const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

export const metadata = {
  title: "Logger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          font.className +
          " bg-gradient-to-r from-blue-100 to-blue-100  via-orange-100"
        }
      >
        {children}
      </body>
    </html>
  );
}
