"use client";
import BarChart from "@/components/UI/Charts/BarChart";
import PieChart from "@/components/UI/Charts/PieChart";
import { CaretRight } from "@phosphor-icons/react/dist/ssr";
import { useState } from "react";

const page = () => {
  return (
    <div className=" md:ml-[300px] md:w-[calc(100%-340px)] w-full bg-white ">
      <div className="xl:w-[80%] px-4">
        <Heading />
        <VisitorsData />
        <DataByGeography />
        <TrafficLogs />
      </div>
    </div>
  );
};

function Heading() {
  return (
    <div className="flex flex-col items-center justify-center gap-8 py-10 mt-16 border-b-2 border-gray-200 ">
      <h1 className=" text-3xl w-full text-center md:text-5xl font-[600]">
        Stats & Insights
      </h1>
      <p className="px-4 md:px-10 text-lg text-center text-gray-700 font-[400]">
        Logger provides a comprehensive set of statistics, offering valuable
        insights into user interactions and engagement on your platform. Here's
        an overview of the types of stats Logger presents:
      </p>
    </div>
  );
}

function VisitorsData() {
  return (
    <div id="visitors" className="py-12 border-b-2">
      <div className="mt-12">
        <div>
          <span className="text-gray-500">count</span>
          <h2 className="text-3xl text-gray-800 font-[450]">Visitors Count</h2>
        </div>
        <div></div>
        <div>
          <div>
            <BarChart totalVisitors="100" uniqueVisitors="69" />
          </div>
        </div>
      </div>
    </div>
  );
}
function DataByGeography() {
  const country = { IN: 65, US: 20, FR: 15 };
  const city = { Lucknow: 65, NYK: 20, LA: 15 };
  const region = { UP: 50, MH: 20, GJ: 15, MP: 15 };
  const [chart, setChart] = useState(1);
  return (
    <div id="geography" className="py-12 border-b-2">
      <div className="">
        <div className="flex flex-col justify-between sm:flex-row">
          <div>
            <span className="text-gray-500">geographical data</span>
            <h2 className="text-3xl text-gray-800 font-[450]">
              Data by geography
            </h2>
          </div>

          <div>
            <select
              className="px-2 py-1 mx-auto text-sm border rounded-md outline-none resize-none w-fit "
              value={1}
              onChange={(e) => setChart(Number(e.target.value))}
            >
              <option value={1}>Country</option>
              <option value={2}>City</option>
              <option value={3}>Region</option>
            </select>
          </div>
        </div>
        <div className="mt-10 ml-8 ">
          <ul className="list-disc ">
            <li>
              Geographical data generated by Logger offers a detailed and
              insightful perspective on the diverse origins of your website or
              application's audience.
            </li>
            <li className="mt-2">
              By capturing information about the locations of visitors, Logger's
              geographical logs provide valuable analytics that can inform
              content localization, marketing strategies, and user experience
              optimization.
            </li>
          </ul>
        </div>
        <div className="mt-10">
          {chart == 1 && <PieChart data={country} />}
          {chart == 2 && <PieChart data={city} />}
          {chart == 3 && <PieChart data={region} />}
        </div>
      </div>
    </div>
  );
}

function TrafficLogs() {
  return (
    <div id="traffic" className="py-12 ">
      <div>
        <span className="text-gray-500">logs</span>
        <h2 className="text-3xl text-gray-800 font-[450]">Traffic Logs</h2>
      </div>
      <div className="mt-5 ml-4 sm:ml-8 ">
        <ul className="list-disc ">
          <li>
            Traffic logs generated by Logger serve as a rich source of
            information, capturing detailed insights into user interactions with
            your website or application.
          </li>
          <li className="mt-2">
            These logs are invaluable for understanding user behavior,
            optimizing content, and making informed decisions to enhance the
            overall user experience.
          </li>
          <li className="mt-2">
            Here's an overview of the key aspects covered by traffic logs
            generated by Logger:
          </li>
        </ul>
      </div>
      <div className="mt-4 ml-4 sm:ml-10">
        <h3 className="font-[450] text-xl mb-2">Visitor Details</h3>
        <div className="ml-4 sm:ml-8">
          <ul className="list-decimal">
            <li className="before:content-['IP_Address:'] before:font-[450]">
              Logger records the IP addresses of visitors, providing insights
              into their geographical locations.
            </li>
            <li className="before:content-['User_Agent:'] before:font-[450]">
              Captures information about the browsers and devices used by
              visitors, aiding in optimizing your platform for various
              environments.
            </li>
          </ul>
        </div>
      </div>
      <div className="mt-4 ml-4 sm:ml-8">
        <h3 className="font-[450] text-xl mb-2">Timestamps</h3>
        <div className="ml-4 sm:ml-8">
          <ul className="list-decimal">
            <li className="">
              Each log entry includes a timestamp, allowing you to analyze
              traffic patterns over specific time intervals.
            </li>
            <li className="">
              Helps identify peak traffic hours, user engagement trends, and
              other temporal patterns.
            </li>
          </ul>
        </div>
      </div>
      <div className="mt-4 ml-4 sm:ml-8">
        <h3 className="font-[450] text-xl mb-2">Referral Sources</h3>
        <div className="ml-4 sm:ml-8">
          <ul className="list-decimal">
            <li className="">
              Reveals the sources from which visitors navigated to your site,
              distinguishing between direct traffic and referrals from external
              platforms.
            </li>
          </ul>
        </div>
      </div>
      <div className="mt-4 ml-4 sm:ml-8">
        <h3 className="font-[450] text-xl mb-2">Geographical Data</h3>
        <div className="ml-4 sm:ml-8">
          <ul className="list-decimal">
            <li className="">
              Logger logs provide information about the geographical
              distribution of your audience, including country, city, and region
              data.
            </li>
            <li className="">
              Useful for tailoring content to specific regions and understanding
              the global reach of your platform.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
export default page;
